# -*- coding: utf-8 -*-
"""LR_2_task_3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IVDGJERBtleFNvKz5w2j96PJwctpV-PE
"""

import numpy as np, matplotlib.pyplot as plt, pywt
x = np.array([1,2,0,1,2,0,0,0,0,1,3,0,11,35,40,22,43,52,35,32,38,45,23,43,23,53,10,19,55,38,37,44,16,22,5,12,32,35,40], dtype=float)
N = len(x)
t = np.arange(N)
fig,(ax1,ax2)=plt.subplots(2,1,figsize=(10,8),sharex=True)
ax1.plot(t,x); ax1.grid(True)
ax1.set_ylabel('Кількість публікацій'); ax1.set_title('Динаміка публікацій')
scales = np.arange(1, N)
cwt, freqs = pywt.cwt(x, scales, 'mexh', sampling_period=1/100.0)
ax2.pcolormesh(t, scales, cwt)
ax2.set_ylim(0,10); ax2.set_ylabel('Масштаб'); ax2.set_xlabel('Час')
ax2.set_title('Скейлограма (Mexican Hat)')
plt.tight_layout(); plt.show()