# -*- coding: utf-8 -*-
"""LR_2_task_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13-BU7UDeCtdaqiml3c4W5XgzYCC7ntTE

# ЛР 2 — Частина 1: Віконне згладжування
"""

# Commented out IPython magic to ensure Python compatibility.

import numpy as np, matplotlib.pyplot as plt
# %matplotlib inline

D = [1,2,0,1,2,0,0,0,0,1,3,0,11,35,40,22,43,52,35,32,38,45,23,43,23,53,10,19,55,38,37,44,16,22,5,12,32,35,40]
D = np.array(D, dtype=float)

def moving_average(x, w):
    x = np.asarray(x, float)
    y = np.full_like(x, np.nan)
    for t in range(len(x)):
        L,R = max(0,t-w), min(len(x), t+w+1)
        y[t] = x[L:R].mean()
    return y

plt.figure()
for w in [1,3,4,8]:
    plt.plot(moving_average(D,w), label=f'w={w}')
plt.plot(D, alpha=0.4, label='orig')
plt.legend(); plt.title('Ковзне середнє'); plt.xlabel('t'); plt.ylabel('значення')
plt.show()

"""**Висновок:** більше вікно — сильніше згладжування, менше локальних деталей."""