# -*- coding: utf-8 -*-
"""LR_2_task_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LHYbekRtlkdgVqBwjG-YrhBJZQIq1I6C
"""

import numpy as np, matplotlib.pyplot as plt
D = np.array([1,2,0,1,2,0,0,0,0,1,3,0,11,35,40,22,43,52,35,32,38,45,23,43,23,53,10,19,55,38,37,44,16,22,5,12,32,35,40], dtype=float)
N = len(D)

M = 8
Z = np.zeros((M, N))
for j in range(M):
    w = 2*j+1
    for k in range(N):
        a = max(0, k-j)
        b = min(N, k+j+1)
        Z[j,k] = D[a:b].mean()

import matplotlib.pyplot as plt
fig,(ax0,ax1,ax2)=plt.subplots(3,1,figsize=(8,9))
ax0.plot(D); ax0.set_title('Рівні згладжування часового ряду')
ax1.plot(Z[M-1]); ax2.pcolormesh(Z)
ax2.set_title('Згладжування')
plt.tight_layout(); plt.show()