# -*- coding: utf-8 -*-
"""LR_2_task_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jZHeznlZK8YNHFRP-EYk5CW76aW7yeB9

# ЛР 2 — Частина 2: Експоненційне згладжування
"""

# Commented out IPython magic to ensure Python compatibility.

import numpy as np, matplotlib.pyplot as plt
# %matplotlib inline

D = [1,2,0,1,2,0,0,0,0,1,3,0,11,35,40,22,43,52,35,32,38,45,23,43,23,53,10,19,55,38,37,44,16,22,5,12,32,35,40]
D = np.array(D, dtype=float)

def exp_smooth(x, alpha):
    s = np.zeros_like(x, float)
    s[0] = x[0]
    for t in range(1,len(x)):
        s[t] = alpha*x[t] + (1-alpha)*s[t-1]
    return s

plt.figure()
for a in [0.2,0.4,0.6,0.8]:
    plt.plot(exp_smooth(D,a), label=f'alpha={a}')
plt.plot(D, alpha=0.4, label='orig')
plt.legend(); plt.title('Експоненційне згладжування'); plt.xlabel('t'); plt.ylabel('значення')
plt.show()

"""**Висновок:** чим менший `alpha`, тим сильніше згладжування (більша інерція)."""