# -*- coding: utf-8 -*-
"""LR_2_task_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OpuIIgwnOKQNDqVNRLBU5sCh1-1O2_er
"""

import numpy as np, matplotlib.pyplot as plt
D = np.array([1,2,0,1,2,0,0,0,0,1,3,0,11,35,40,22,43,52,35,32,38,45,23,43,23,53,10,19,55,38,37,44,16,22,5,12,32,35,40], dtype=float)
N = len(D)

M = 5
Z = np.zeros((M, N))
for j in range(M):
    a = (j+1)/M
    Z[j,0] = D[0]
    for k in range(1,N):
        Z[j,k] = a*D[k] + (1-a)*Z[j,k-1]

import matplotlib.pyplot as plt
fig,(ax0,ax1,ax2)=plt.subplots(3,1,figsize=(8,9))
ax0.plot(D); ax0.set_title('Рівні експоненційного згладжування')
ax1.plot(Z[M//2]); ax2.pcolormesh(Z)
ax2.set_title('Згладжування')
plt.tight_layout(); plt.show()